mod commands;
mod operations;
mod services;
mod storage;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(operations::OperationCoordinator::default())
        .manage(services::agent::AgentCoordinator::default())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            commands::agent::cancel_agent_action_plan,
            commands::agent::clear_agent_session,
            commands::agent::confirm_agent_action_plan,
            commands::agent::create_agent_cleanup_plan,
            commands::agent::delete_deepseek_api_key,
            commands::agent::delete_nexus_api_key,
            commands::agent::get_agent_settings,
            commands::agent::save_agent_model,
            commands::agent::set_deepseek_api_key,
            commands::agent::set_nexus_api_key,
            commands::agent::start_agent_turn,
            commands::agent::test_agent_connection,
            commands::agent::test_nexus_connection,
            commands::app::get_app_info,
            commands::game::detect_game_directory,
            commands::game::get_game_directory_status,
            commands::game::get_game_text_settings,
            commands::game::save_game_directory,
            commands::game::save_game_text_language,
            commands::knowledge::delete_knowledge_pack,
            commands::knowledge::get_game_entity_relations,
            commands::knowledge::get_knowledge_status,
            commands::knowledge::install_knowledge_pack,
            commands::knowledge::lookup_game_entities,
            commands::knowledge::search_knowledge,
            commands::mod_analysis::analyze_installed_mod,
            commands::mod_library::apply_conflict_order,
            commands::mod_library::apply_mod_remap,
            commands::mod_library::batch_update_mods,
            commands::mod_library::create_mod_category,
            commands::mod_library::create_mod_branch_group,
            commands::mod_library::delete_mod_category,
            commands::mod_library::disable_mod,
            commands::mod_library::enable_mod,
            commands::mod_library::get_mod_conflict_report,
            commands::mod_library::get_mod_library_status,
            commands::mod_library::get_mod_remap_details,
            commands::mod_library::get_mod_workspace_snapshot,
            commands::mod_library::refresh_mod_workspace_snapshot,
            commands::mod_library::install_mod_from_archive,
            commands::mod_library::install_mod_from_candidate,
            commands::mod_library::install_mod_branches,
            commands::mod_library::install_mod_from_folder,
            commands::mod_library::import_legacy_box_mods,
            commands::mod_library::list_installed_mods,
            commands::mod_library::list_mod_categories,
            commands::mod_library::move_conflict_participant,
            commands::mod_library::move_mod_library_item,
            commands::mod_library::move_mod_library_items,
            commands::mod_library::open_installed_mod_folder,
            commands::mod_library::open_mod_cleanup_candidate_folder,
            commands::mod_library::preview_apply_conflict_order,
            commands::mod_library::preview_disable_mod,
            commands::mod_library::preview_enable_mod,
            commands::mod_library::preview_mod_import,
            commands::mod_library::preview_mod_remap,
            commands::mod_library::preview_restore_all_mods,
            commands::mod_library::preview_uninstall_mod,
            commands::mod_library::rename_mod_category,
            commands::mod_library::rename_mod_branch_group,
            commands::mod_library::remove_mods_from_branch_group,
            commands::mod_library::replace_mod_library_order,
            commands::mod_library::refresh_game_mod_states,
            commands::mod_library::restore_mod_library_import_order,
            commands::mod_library::restore_all_mods,
            commands::mod_library::scan_legacy_box_mods,
            commands::mod_library::uninstall_mod,
            commands::mod_library::update_mod_metadata,
            commands::mod_library::update_mod_categories,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
